### ISSUE TITLE
Possibility of adding --testLocationInResults support

### ISSUE THREAD

**Issue by rtbenfield** [jest-community/jest-editor-support#2]
I am working on a test adapter implementation for the [VS Code Test Explorer](https://github.com/hbenl/vscode-test-explorer) extension and it would be beneficial to have the line number reported with the tests. I found that I can do this by overriding the `createProcess` option to inject the `--testLocationInResults` argument and pass that along to the `createProcess` function from `jest-editor-support/build/Process.js`. Would it be beneficial to the project to add this as an option? If so, I would be glad to make an attempt at a PR.

**Comment by connectdotz** [comment]
we didn't use jest reported locations and instead opt to parse the source (test) file followed by merging with test result (see [test_reconciler.js](https://github.com/jest-community/jest-editor-support/blob/master/src/test_reconciler.js))... I suspect you might encounter some problems with jest reported locations for transpired files, such as typescript or babel`... 

If for some reason you decide not to use test_reconciler.js, you can always customize the runner by passing `--testLocationInResults` via  `workspace.pathToJest` ...

**Comment by rtbenfield** [comment]
I didn't realize that was the intent of `TestReconciler`. It looks like that will accomplish everything I am looking for, and from your information it sounds like it will also be more accurate. Thanks for the information!

**Comment by SimenB** [comment]
>I suspect you might encounter some problems with jest reported locations for transpired files, such as typescript or babel`...

They go through the source map, so they'll be as accurate as source maps allows us to be

**Comment by connectdotz** [comment]
> They go through the source map, so they'll be as accurate as source maps allows us to be

indeed. However, many projects, unfortunately, do struggle with sourceMap, we found that we could, for the most part, matching tests by their names, therefore, bypassing the nasty sourceMap issues altogether.  

Having said that, we recently encountered a template-literal-string name matching issue and realized to have location information to fall back to is probably better than not.  Therefore, we did end up adding the '--testLocationInResults' in the Runner (#9).

**Comment by seanpoulter** [comment]
How did you find testing with `--testLocationInResults` on affects the performance @connectdotz?

**Comment by connectdotz** [comment]
I do see ~ 4% performance degradation in a few test runs... 

for example, without the flag, I can run vscode-jest `yarn test` in 14.165s, with the '--testLocationInResults', it ran for 14.701s

do you think it is a significant performance hit?
