### ISSUE TITLE
What's the status of detecting describe blocks?

### ISSUE THREAD

**Issue by captbaritone** [jest-community/jest-editor-support#3]
I see there is some code in `babylon_parser.js` for extracting describe blocks, but I don't see that code in any of the releases. With the move out of the Jest mono-repo it's a bit hard to see when the last release was cut.

Is this a feature which has been added but not yet released?

**Comment by captbaritone** [comment]
Ping @orta

**Comment by orta** [comment]
Sorry, I missed the create email.

Hrm, yeah, I think it is shipped but not released. 

Now that I think about it, TBH, I think this entirely library could just go back into vscode-jest for simplicity. Are you using it in anything other than that app?

**Comment by orta** [comment]
Ah, majestic uses this. OK. I'll look at making a release now.

**Comment by captbaritone** [comment]
Awesome! Thanks for the quick response. We're using it internally in Nuclide.

**Comment by orta** [comment]
I've got access and deployed as 25.0.0 👍

**Comment by captbaritone** [comment]
Thanks!
