### ISSUE TITLE
Cannot find @babel/traverse

### ISSUE THREAD

**Issue by nithinpeter** [jest-community/jest-editor-support#5]
When I try to use the package I get `Cannot find @babel/traverse` error. Maybe the [dependency listed](https://github.com/jest-community/jest-editor-support/blob/master/package.json#L27) should be changed to `@babel/traverse`. Manually installing `@babel/traverse` did fix the problem for me!

**Comment by SimenB** [comment]
Yeah, seems like an error to me, the dependency used is indeed `@babel/traverse`: https://github.com/jest-community/jest-editor-support/blob/cdef315377730c467519d723230a59bdc997dbbe/src/Snapshot.js#L15

Wanna send a PR fixing it?

/cc @orta

**Comment by nithinpeter** [comment]
👍 Thanks for fixing!
