### ISSUE TITLE
Parsing fails when using test.each`table`(name, fn, timeout)

### ISSUE THREAD

**Issue by grant-wilson** [jest-community/jest-editor-support#53]
From the Jest docs, you can structure a describe or a test like so
```typescript
test.each`
  a    | b    | expected
  ${1} | ${1} | ${2}
  ${1} | ${2} | ${3}
  ${2} | ${1} | ${3}
`('returns $expected when $a is added $b', ({a, b, expected}) => {
  expect(a + b).toBe(expected);
});
```
[reference](https://jestjs.io/docs/en/api#2--testeachtablename-fn-timeout-)

jest-editor-support does not recognize these expressions as tests in either v28.0.0 or v27.2.0.
I think this is similar, but different from the discussion had in https://github.com/jest-community/jest-editor-support/issues/29#issuecomment-578521119

**Comment by grant-wilson** [comment]
There may be more to it, but this code seems relevant:
## v28.0.0
https://github.com/jest-community/jest-editor-support/blob/13d4ee150904d64142bf3ce0461caabbb6c7c491/src/parsers/babel_parser.js#L79-L85

## v27.2.0

### js

https://github.com/jest-community/jest-editor-support/blob/a9171e98063c9316d7b16d6086048f55f35e5709/src/parsers/babylon_parser.js#L72-L79

### ts

https://github.com/jest-community/jest-editor-support/blob/a9171e98063c9316d7b16d6086048f55f35e5709/src/parsers/typescript_parser.js#L93

---

I believe with babel the tagged template literal can be filtered with `node.expression.callee.type === 'TaggedTemplateExpression'`.
And the name under `node.expression.callee.tag.object.name`.

With ts more info can be found under `node.expression.tag.expression`.

**Comment by connectdotz** [comment]
@grant-wilson feel free to take a look at PR #57

**Comment by grant-wilson** [comment]
@connectdotz this looks like a good resolution for v28.0.0. Thank you!
