### ISSUE TITLE
Addressing issue facebook/jest#4910

### ISSUE THREAD

**Issue by jackHedaya** [jest-community/jest-editor-support#8]
I'd like to reopen the issue found in https://github.com/facebook/jest/issues/4910 that discusses the use of string literals in test names.

**Comment by seanpoulter** [comment]
Sure, any thoughts on how to move it forward? It has been a while since I looked at it and ended up with a bunch of questions in this comment:

https://github.com/facebook/jest/issues/4910#issuecomment-345478728.

**Comment by connectdotz** [comment]
we have added template literal string parsing support a few months ago ([here](https://github.com/jest-community/jest-editor-support/blob/171f845655afe6929cd97a2bab7c3948e05e916f/src/parsers/babylon_parser.js#L58)), but just hasn't integrated the new package with vscode-jest, which I am trying to do now.

**Comment by seanpoulter** [comment]
Oh heck yea! 🥇 Thanks @connectdotz!
Would you have capacity to review the PR @jackHedaya? 😉

**Comment by jackHedaya** [comment]
Going to give it a shot now, though I recommend someone else double checking as this is my first Jest PR review.

**Comment by seanpoulter** [comment]
How's it working for you now @jackHedaya?

**Comment by jackHedaya** [comment]
Works fine now, thank you!
